### ISSUE TITLE
v1.1.6.8 detected as a trojan

### ISSUE THREAD

**Issue by ericgl** [joshuacline/ShaZZam#1]
v1.1.6.7 and v1.1.6.8 detected as a trojan:

![image](https://github.com/user-attachments/assets/19516313-a7bd-46a1-9bfd-86078164ce37)

**Comment by joshuacline** [comment]
I have submitted the report to microsoft security intelligence.
![20240721_143847](https://github.com/user-attachments/assets/fc6f8725-6338-4295-b633-6ecd270342fc)

**Comment by joshuacline** [comment]
Don't know how this occurred in the first place, however, it has been resolved.
![20240722_101019](https://github.com/user-attachments/assets/9e6dd7a8-c22f-4a98-b2a1-866b2e333500)
