### ISSUE TITLE
`ECHO.` isn't optimal

### ISSUE THREAD

**Issue by God-damnit-all** [joshuacline/ShaZZam#3]
https://stackoverflow.com/a/6379940 explains why `ECHO.` should be avoided.

The two main recommendations are `ECHO/`,which only has issues when a string starts with a question mark, and `ECHO(`, which works well but just looks horribly wrong.

https://www.dostips.com/forum/viewtopic.php?f=3&t=774&start=30#p67479 This post goes over the many options, and the proceeding posts mention that `ECHO(` passes the most parsing tests.

I recommend `ECHO/` for most cases.

**Comment by joshuacline** [comment]
![Alt text](https://i.imgflip.com/920y14.jpg "00")

**Comment by God-damnit-all** [comment]
Uhh... okay...? Was just trying to help.
